sudo: required

services:
  - docker

install:
  - docker build --rm --no-cache -t cryptout/sickrage ../sickrage

script:
  - ./rundocker.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push cryptout/sickrage:latest;
    fi

notifications:
  email: false
